import type { Place } from "./overpass";

// Fotos Unsplash por categoria (IDs verificados)
export const FOTOS_CATEGORIA: Record<string, string> = {
  parques:      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80",
  museus:       "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=600&q=80",
  cultura:      "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=600&q=80",
  restaurantes: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
  bares:        "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&q=80",
  shows:        "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80",
  feiras:       "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=600&q=80",
  esportes:     "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600&q=80",
};

export interface PlaceEx extends Place {
  foto?: string;
  descricao?: string;
}

export const CAMPO_GRANDE: PlaceEx[] = [
  // ── PARQUES ──────────────────────────────────────────────────────────────
  {
    id: "cgr-p1",
    nome: "Parque das Nações Indígenas",
    categoria: "parques",
    categoriaLabel: "Parque",
    emoji: "🌿",
    cor: "from-teal-500 to-emerald-700",
    lat: -20.4765, lng: -54.5895,
    endereco: "Av. Afonso Pena s/n — Parque das Nações Indígenas",
    horario: "Seg–Dom 05:00–20:00",
    descricao: "O maior parque urbano de Campo Grande, com lago, trilhas ecológicas e o Museu das Culturas Dom Bosco nas redondezas.",
    foto: "https://images.unsplash.com/photo-1563195917-16b0e3c3bc8f?w=600&q=80",
  },
  {
    id: "cgr-p2",
    nome: "Parque dos Ipês",
    categoria: "parques",
    categoriaLabel: "Parque",
    emoji: "🌿",
    cor: "from-teal-500 to-emerald-700",
    lat: -20.4910, lng: -54.6410,
    endereco: "R. Monsenhor Henrique — Carandá Bosque",
    horario: "Seg–Dom 06:00–18:00",
    descricao: "Parque arborizado no bairro Carandá Bosque, ideal para caminhadas e piqueniques.",
    foto: FOTOS_CATEGORIA.parques,
  },
  {
    id: "cgr-p3",
    nome: "Parque Estadual do Prosa",
    categoria: "parques",
    categoriaLabel: "Reserva",
    emoji: "🌿",
    cor: "from-teal-500 to-emerald-700",
    lat: -20.4634, lng: -54.5718,
    endereco: "Av. Fernando Corrêa da Costa — Prosa",
    horario: "Ter–Dom 07:00–17:00",
    descricao: "Reserva ecológica urbana com trilhas no cerrado, fauna local e Centro de Reabilitação de Animais Silvestres (CRAS).",
    foto: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80",
  },

  // ── MUSEUS ───────────────────────────────────────────────────────────────
  {
    id: "cgr-m1",
    nome: "Museu das Culturas Dom Bosco",
    categoria: "museus",
    categoriaLabel: "Museu",
    emoji: "🏛️",
    cor: "from-amber-500 to-yellow-700",
    lat: -20.4766, lng: -54.5897,
    endereco: "Parque das Nações Indígenas s/n",
    horario: "Ter–Dom 08:00–17:00",
    website: "http://www.mcdb.org.br",
    descricao: "Acervo com mais de 50 mil peças de culturas indígenas sul-americanas, incluindo a coleção salesiana. Um dos maiores do Brasil.",
    foto: "https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=600&q=80",
  },
  {
    id: "cgr-m2",
    nome: "MARCO — Museu de Arte Contemporânea",
    categoria: "museus",
    categoriaLabel: "Museu",
    emoji: "🏛️",
    cor: "from-amber-500 to-yellow-700",
    lat: -20.4625, lng: -54.5870,
    endereco: "Av. Calógeras, 2050 — Centro",
    horario: "Ter–Sex 08:00–17:30 · Sáb–Dom 10:00–17:00",
    descricao: "Museu de arte contemporânea com exposições temporárias e acervo permanente de artistas de Mato Grosso do Sul.",
    foto: FOTOS_CATEGORIA.museus,
  },
  {
    id: "cgr-m3",
    nome: "Museu Estadual do MS",
    categoria: "museus",
    categoriaLabel: "Museu",
    emoji: "🏛️",
    cor: "from-amber-500 to-yellow-700",
    lat: -20.4614, lng: -54.6150,
    endereco: "Parque dos Poderes — Bloco 3",
    horario: "Ter–Dom 08:00–17:00",
    descricao: "Acervo histórico, arqueológico e natural do estado de Mato Grosso do Sul. Entrada gratuita.",
    foto: "https://images.unsplash.com/photo-1564934304050-1b83c5f64e8b?w=600&q=80",
  },

  // ── CULTURA ──────────────────────────────────────────────────────────────
  {
    id: "cgr-c1",
    nome: "Teatro Glauce Rocha",
    categoria: "cultura",
    categoriaLabel: "Teatro",
    emoji: "🎭",
    cor: "from-purple-500 to-violet-700",
    lat: -20.4612, lng: -54.6134,
    endereco: "Av. Noroeste, 5140 — Centro",
    descricao: "Principal teatro de Campo Grande. Apresentações de dança, teatro, música e ópera durante todo o ano.",
    foto: FOTOS_CATEGORIA.cultura,
  },
  {
    id: "cgr-c2",
    nome: "SESC Campo Grande",
    categoria: "cultura",
    categoriaLabel: "Cultural",
    emoji: "🎭",
    cor: "from-purple-500 to-violet-700",
    lat: -20.4638, lng: -54.6175,
    endereco: "R. Antonio Maria Coelho, 1435 — Centro",
    horario: "Seg–Sex 08:00–21:00 · Sáb 08:00–18:00",
    website: "https://www.sescms.com.br",
    descricao: "Centro cultural com cinema, teatro, exposições, shows e atividades esportivas.",
    foto: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=600&q=80",
  },
  {
    id: "cgr-c3",
    nome: "Casa de Ensaios — Morada dos Baís",
    categoria: "cultura",
    categoriaLabel: "Cultural",
    emoji: "🎭",
    cor: "from-purple-500 to-violet-700",
    lat: -20.4610, lng: -54.6132,
    endereco: "Av. Noroeste, 5140 — Centro",
    horario: "Ter–Dom 18:00–23:00",
    descricao: "Casa histórica que abriga eventos culturais, shows e o restaurante regional Morada dos Baís.",
    foto: "https://images.unsplash.com/photo-1513628253939-010e64ac66cd?w=600&q=80",
  },

  // ── RESTAURANTES ─────────────────────────────────────────────────────────
  {
    id: "cgr-r1",
    nome: "Morada dos Baís",
    categoria: "restaurantes",
    categoriaLabel: "Restaurante",
    emoji: "🍽️",
    cor: "from-orange-400 to-red-500",
    lat: -20.4610, lng: -54.6132,
    endereco: "Av. Noroeste, 5140 — Centro",
    horario: "Ter–Dom 11:30–15:00 · Sex–Sáb 19:00–23:00",
    descricao: "Restaurante na casa histórica dos Baís, com culinária regional pantaneira e shows de música ao vivo.",
    foto: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80",
  },
  {
    id: "cgr-r2",
    nome: "Fogo Caipira",
    categoria: "restaurantes",
    categoriaLabel: "Regional",
    emoji: "🍽️",
    cor: "from-orange-400 to-red-500",
    lat: -20.4880, lng: -54.6130,
    endereco: "R. Joaquim Murtinho, 2355 — Santa Fé",
    horario: "Seg–Dom 11:00–15:00",
    descricao: "Culinária pantaneira e caipira com buffet de pratos típicos como arroz carreteiro, pacu e galinhada.",
    foto: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80",
  },
  {
    id: "cgr-r3",
    nome: "Cantina Romana",
    categoria: "restaurantes",
    categoriaLabel: "Italiano",
    emoji: "🍽️",
    cor: "from-orange-400 to-red-500",
    lat: -20.4735, lng: -54.6070,
    endereco: "R. Dom Aquino, 2027 — Centro",
    horario: "Ter–Dom 11:30–14:30 · Ter–Sáb 19:00–23:00",
    telefone: "(67) 3324-2100",
    descricao: "Uma das mais tradicionais cantinas italianas de Campo Grande, com massas artesanais e ambiente familiar.",
    foto: "https://images.unsplash.com/photo-1498579150354-977475b7ea0b?w=600&q=80",
  },
  {
    id: "cgr-r4",
    nome: "Churrascaria Rancho do Pantanal",
    categoria: "restaurantes",
    categoriaLabel: "Churrascaria",
    emoji: "🍽️",
    cor: "from-orange-400 to-red-500",
    lat: -20.4930, lng: -54.6320,
    endereco: "Av. Duque de Caxias — Jardim Veraneio",
    horario: "Seg–Dom 11:30–15:00 · Sex–Dom 19:00–22:30",
    descricao: "Churrascaria rodízio com cortes do Pantanal e serviço de qualidade.",
    foto: FOTOS_CATEGORIA.restaurantes,
  },

  // ── BARES ────────────────────────────────────────────────────────────────
  {
    id: "cgr-b1",
    nome: "Camelot Bar & Arte",
    categoria: "bares",
    categoriaLabel: "Bar cultural",
    emoji: "🍺",
    cor: "from-yellow-500 to-amber-600",
    lat: -20.4580, lng: -54.6040,
    endereco: "R. Joaquim Nabuco, 77 — Centro",
    horario: "Qui–Sáb 19:00–02:00",
    telefone: "(67) 3025-2050",
    descricao: "Bar cultural com arte, música ao vivo, chopp artesanal e petiscos. Point da cena cultural de Campo Grande.",
    foto: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=600&q=80",
  },
  {
    id: "cgr-b2",
    nome: "Bar do Bigode",
    categoria: "bares",
    categoriaLabel: "Boteco",
    emoji: "🍺",
    cor: "from-yellow-500 to-amber-600",
    lat: -20.4701, lng: -54.6200,
    endereco: "R. 14 de Julho — Região Central",
    horario: "Seg–Sáb 17:00–00:00",
    descricao: "Boteco tradicional e popular, frequentado por moradores da cidade há décadas. Boa cerveja gelada e tira-gosto.",
    foto: FOTOS_CATEGORIA.bares,
  },
  {
    id: "cgr-b3",
    nome: "Choperia Alvorada",
    categoria: "bares",
    categoriaLabel: "Choperia",
    emoji: "🍺",
    cor: "from-yellow-500 to-amber-600",
    lat: -20.4650, lng: -54.5920,
    endereco: "Av. Afonso Pena — Jardim dos Estados",
    horario: "Ter–Dom 17:00–01:00",
    descricao: "Choperia com ambiente amplo, petiscos variados e música ao vivo nos fins de semana.",
    foto: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
  },
  {
    id: "cgr-b4",
    nome: "Bar Soberano",
    categoria: "bares",
    categoriaLabel: "Bar universitário",
    emoji: "🍺",
    cor: "from-yellow-500 to-amber-600",
    lat: -20.4510, lng: -54.6120,
    endereco: "Próximo à UFMS — Cidade Universitária",
    horario: "Seg–Sáb 17:00–00:00",
    descricao: "Ponto de encontro dos estudantes da UFMS. Ambiente descontraído, preços acessíveis e sempre animado.",
    foto: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&q=80",
  },

  // ── FEIRAS ───────────────────────────────────────────────────────────────
  {
    id: "cgr-f1",
    nome: "Feira Central de Campo Grande",
    categoria: "feiras",
    categoriaLabel: "Feira gastronômica",
    emoji: "🛍️",
    cor: "from-pink-400 to-rose-500",
    lat: -20.4502, lng: -54.6065,
    endereco: "R. 14 de Julho, 4445 — Feira Central",
    horario: "Qui–Sáb 17:00–23:00 · Dom 07:00–14:00",
    descricao: "Feira tradicional e famosa com yakisoba, espetinhos, sobá e regionais. Ponto turístico gastronômico da cidade.",
    foto: "https://images.unsplash.com/photo-1555992336-03a23c7b20ee?w=600&q=80",
  },
  {
    id: "cgr-f2",
    nome: "Casa do Artesão de MS",
    categoria: "feiras",
    categoriaLabel: "Artesanato",
    emoji: "🛍️",
    cor: "from-pink-400 to-rose-500",
    lat: -20.4610, lng: -54.6152,
    endereco: "Av. Calógeras, 2050 — Centro",
    horario: "Seg–Sex 07:30–17:30 · Sáb 07:30–13:30",
    telefone: "(67) 3321-3521",
    descricao: "Espaço com artesanatos típicos de MS: cerâmica, couro, madeira, bijuterias e produtos do cerrado.",
    foto: FOTOS_CATEGORIA.feiras,
  },
  {
    id: "cgr-f3",
    nome: "Feira do Horto Florestal",
    categoria: "feiras",
    categoriaLabel: "Feira livre",
    emoji: "🛍️",
    cor: "from-pink-400 to-rose-500",
    lat: -20.4422, lng: -54.5927,
    endereco: "Parque Horto Florestal — Bairro Novos Estados",
    horario: "Sáb 07:00–13:00",
    descricao: "Feira de fim de semana com hortifrúti orgânico, artesanato e comida regional em um parque arborizado.",
    foto: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80",
  },

  // ── SHOWS ────────────────────────────────────────────────────────────────
  {
    id: "cgr-s1",
    nome: "Arena Pantanal CG",
    categoria: "shows",
    categoriaLabel: "Arena de eventos",
    emoji: "🎵",
    cor: "from-violet-600 to-purple-800",
    lat: -20.4930, lng: -54.6150,
    endereco: "Av. Gury Marques — Pioneiros",
    descricao: "Arena para grandes shows e eventos com capacidade para milhares de pessoas.",
    foto: FOTOS_CATEGORIA.shows,
  },
  {
    id: "cgr-s2",
    nome: "Clube de Campo de Campo Grande",
    categoria: "shows",
    categoriaLabel: "Shows & festas",
    emoji: "🎵",
    cor: "from-violet-600 to-purple-800",
    lat: -20.5100, lng: -54.6450,
    endereco: "Av. Duque de Caxias — Carandá Bosque",
    horario: "Sex–Sáb 20:00–02:00",
    descricao: "Espaço de festas e shows com música ao vivo, DJs e eventos culturais nos fins de semana.",
    foto: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=600&q=80",
  },

  // ── ESPORTES ─────────────────────────────────────────────────────────────
  {
    id: "cgr-e1",
    nome: "Estádio Universitário Morenão",
    categoria: "esportes",
    categoriaLabel: "Estádio",
    emoji: "⚽",
    cor: "from-emerald-500 to-teal-600",
    lat: -20.4544, lng: -54.5981,
    endereco: "Av. Universitária s/n — UFMS",
    website: "https://www.operario.com.br",
    descricao: "Casa do Operário FC e da Seleção de MS. Palco de jogos do Campeonato Sul-Mato-Grossense.",
    foto: FOTOS_CATEGORIA.esportes,
  },
  {
    id: "cgr-e2",
    nome: "Centro Olímpico de Campo Grande",
    categoria: "esportes",
    categoriaLabel: "Poliesportivo",
    emoji: "⚽",
    cor: "from-emerald-500 to-teal-600",
    lat: -20.4570, lng: -54.6010,
    endereco: "Av. Afonso Pena — Centro-Oeste",
    horario: "Seg–Sex 07:00–21:00 · Sáb 07:00–17:00",
    descricao: "Complexo esportivo com piscinas olímpicas, quadras, ginásio e pistas de atletismo.",
    foto: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&q=80",
  },
  {
    id: "cgr-e3",
    nome: "Club Náutico Campo Grande",
    categoria: "esportes",
    categoriaLabel: "Clube náutico",
    emoji: "⚽",
    cor: "from-emerald-500 to-teal-600",
    lat: -20.5200, lng: -54.6700,
    endereco: "Rodovia BR-163, km 2 — Saída Sidrolândia",
    horario: "Sáb–Dom 08:00–18:00",
    descricao: "Clube com lago artificial, esportes aquáticos, pesca esportiva e lazer para toda a família.",
    foto: "https://images.unsplash.com/photo-1567606404787-2a8b4d98ea87?w=600&q=80",
  },
];

export function getCGPlacesByCategoria(cats: string[]): PlaceEx[] {
  if (!cats.length || cats.includes("todos")) return CAMPO_GRANDE;
  return CAMPO_GRANDE.filter((p) => cats.includes(p.categoria));
}
