import type { Place } from "./overpass";

// Lugares reais curados de Campo Grande, MS
// Coordenadas aproximadas para abertura no Maps via nome
export const CAMPO_GRANDE: Place[] = [
  // ──────────── PARQUES ────────────
  {
    id: "cgr-p1",
    nome: "Parque das Nações Indígenas",
    categoria: "parques",
    categoriaLabel: "Parque",
    emoji: "🌿",
    cor: "from-teal-500 to-emerald-700",
    lat: -20.4765,
    lng: -54.5895,
    endereco: "Av. Afonso Pena s/n — Parque das Nações Indígenas",
    horario: "Mo-Su 05:00-20:00",
  },
  {
    id: "cgr-p2",
    nome: "Parque dos Ipês",
    categoria: "parques",
    categoriaLabel: "Parque",
    emoji: "🌿",
    cor: "from-teal-500 to-emerald-700",
    lat: -20.4910,
    lng: -54.6410,
    endereco: "R. Monsenhor Henrique s/n — Carandá Bosque",
    horario: "Mo-Su 06:00-18:00",
  },
  {
    id: "cgr-p3",
    nome: "Parque Estadual do Prosa",
    categoria: "parques",
    categoriaLabel: "Parque",
    emoji: "🌿",
    cor: "from-teal-500 to-emerald-700",
    lat: -20.4634,
    lng: -54.5718,
    endereco: "Av. Fernando Corrêa da Costa — Prosa",
    horario: "Mo-Su 07:00-17:00",
  },

  // ──────────── MUSEUS ────────────
  {
    id: "cgr-m1",
    nome: "Museu das Culturas Dom Bosco",
    categoria: "museus",
    categoriaLabel: "Museu",
    emoji: "🏛️",
    cor: "from-amber-500 to-yellow-700",
    lat: -20.4766,
    lng: -54.5897,
    endereco: "Parque das Nações Indígenas s/n",
    horario: "Tu-Su 08:00-17:00",
    website: "http://www.mcdb.org.br",
  },
  {
    id: "cgr-m2",
    nome: "MARCO — Museu de Arte Contemporânea",
    categoria: "museus",
    categoriaLabel: "Museu",
    emoji: "🏛️",
    cor: "from-amber-500 to-yellow-700",
    lat: -20.4625,
    lng: -54.5870,
    endereco: "Av. Calógeras, 1118 — Centro",
    horario: "Tu-Fr 08:00-17:30; Sa-Su 10:00-17:00",
  },
  {
    id: "cgr-m3",
    nome: "Museu Estadual do Mato Grosso do Sul",
    categoria: "museus",
    categoriaLabel: "Museu",
    emoji: "🏛️",
    cor: "from-amber-500 to-yellow-700",
    lat: -20.4614,
    lng: -54.6150,
    endereco: "Av. Desembargador Leão Neto do Carmo s/n — Bloco 3",
    horario: "Tu-Su 08:00-17:00",
  },

  // ──────────── CULTURA ────────────
  {
    id: "cgr-c1",
    nome: "Teatro Glauce Rocha",
    categoria: "cultura",
    categoriaLabel: "Teatro",
    emoji: "🎭",
    cor: "from-purple-500 to-violet-700",
    lat: -20.4612,
    lng: -54.6134,
    endereco: "Av. Noroeste, 5140 — Centro",
    website: "http://www.fcms.ms.gov.br",
  },
  {
    id: "cgr-c2",
    nome: "SESC Campo Grande — Teatro",
    categoria: "cultura",
    categoriaLabel: "Cultural",
    emoji: "🎭",
    cor: "from-purple-500 to-violet-700",
    lat: -20.4638,
    lng: -54.6175,
    endereco: "R. Antonio Maria Coelho, 1435 — Centro",
    horario: "Mo-Fr 08:00-21:00; Sa 08:00-18:00",
    website: "http://www.sescms.com.br",
  },
  {
    id: "cgr-c3",
    nome: "Cine Cultura Campo Grande",
    categoria: "cultura",
    categoriaLabel: "Cinema",
    emoji: "🎭",
    cor: "from-purple-500 to-violet-700",
    lat: -20.4601,
    lng: -54.6152,
    endereco: "Av. Afonso Pena, 2270 — Centro",
  },

  // ──────────── RESTAURANTES ────────────
  {
    id: "cgr-r1",
    nome: "Morada dos Baís",
    categoria: "restaurantes",
    categoriaLabel: "Restaurante",
    emoji: "🍽️",
    cor: "from-orange-400 to-red-500",
    lat: -20.4610,
    lng: -54.6132,
    endereco: "Av. Noroeste, 5140 — Centro",
    horario: "Tu-Su 11:00-15:00; Fr-Sa 19:00-23:00",
    website: "http://www.moradadosbais.com.br",
  },
  {
    id: "cgr-r2",
    nome: "Fogo Caipira",
    categoria: "restaurantes",
    categoriaLabel: "Restaurante",
    emoji: "🍽️",
    cor: "from-orange-400 to-red-500",
    lat: -20.4880,
    lng: -54.6130,
    endereco: "R. Joaquim Murtinho, 2355 — Santa Fé",
    horario: "Mo-Su 11:00-15:00",
  },
  {
    id: "cgr-r3",
    nome: "Cantina Romana",
    categoria: "restaurantes",
    categoriaLabel: "Restaurante",
    emoji: "🍽️",
    cor: "from-orange-400 to-red-500",
    lat: -20.4735,
    lng: -54.6070,
    endereco: "R. Dom Aquino, 2027 — Centro",
    horario: "Tu-Su 11:30-14:30; Tu-Sa 19:00-23:00",
    telefone: "(67) 3324-2100",
  },
  {
    id: "cgr-r4",
    nome: "Churrascaria Rancho do Pantanal",
    categoria: "restaurantes",
    categoriaLabel: "Churrascaria",
    emoji: "🍽️",
    cor: "from-orange-400 to-red-500",
    lat: -20.4930,
    lng: -54.6320,
    endereco: "Av. Duque de Caxias, 2680 — Jardim Veraneio",
    horario: "Mo-Su 11:30-15:00; Fr-Su 19:00-22:30",
  },
  {
    id: "cgr-r5",
    nome: "Dui Restaurante",
    categoria: "restaurantes",
    categoriaLabel: "Restaurante",
    emoji: "🍽️",
    cor: "from-orange-400 to-red-500",
    lat: -20.4875,
    lng: -54.6205,
    endereco: "R. Bahia, 686 — Bairro Monte Castelo",
    horario: "Tu-Sa 12:00-14:30; Tu-Sa 19:30-23:00",
  },

  // ──────────── BARES ────────────
  {
    id: "cgr-b1",
    nome: "Camelot Bar & Arte",
    categoria: "bares",
    categoriaLabel: "Bar",
    emoji: "🍺",
    cor: "from-yellow-500 to-amber-600",
    lat: -20.4580,
    lng: -54.6040,
    endereco: "R. Joaquim Nabuco, 77 — Centro",
    horario: "Th-Sa 19:00-02:00",
    telefone: "(67) 3025-2050",
  },
  {
    id: "cgr-b2",
    nome: "Boteco do Seu Carlão",
    categoria: "bares",
    categoriaLabel: "Boteco",
    emoji: "🍺",
    cor: "from-yellow-500 to-amber-600",
    lat: -20.4701,
    lng: -54.6060,
    endereco: "R. 14 de Julho, 992 — Amambaí",
    horario: "Mo-Sa 17:00-00:00",
  },
  {
    id: "cgr-b3",
    nome: "Choperia Tropical",
    categoria: "bares",
    categoriaLabel: "Bar",
    emoji: "🍺",
    cor: "from-yellow-500 to-amber-600",
    lat: -20.4720,
    lng: -54.5990,
    endereco: "Av. Afonso Pena, 4067 — Jardim dos Estados",
    horario: "Tu-Su 17:00-01:00",
  },
  {
    id: "cgr-b4",
    nome: "Bar Soberano",
    categoria: "bares",
    categoriaLabel: "Bar",
    emoji: "🍺",
    cor: "from-yellow-500 to-amber-600",
    lat: -20.4510,
    lng: -54.6120,
    endereco: "Av. Fernando Corrêa da Costa, 1700 — UFMS",
    horario: "Mo-Sa 17:00-00:00",
  },

  // ──────────── FEIRAS ────────────
  {
    id: "cgr-f1",
    nome: "Feira Central de Campo Grande",
    categoria: "feiras",
    categoriaLabel: "Feira",
    emoji: "🛍️",
    cor: "from-pink-400 to-rose-500",
    lat: -20.4502,
    lng: -54.6065,
    endereco: "R. 14 de Julho, 4445 — Jardim Veraneio",
    horario: "Th-Sa 17:00-23:00; Su 07:00-14:00",
  },
  {
    id: "cgr-f2",
    nome: "Casa do Artesão de MS",
    categoria: "feiras",
    categoriaLabel: "Artesanato",
    emoji: "🛍️",
    cor: "from-pink-400 to-rose-500",
    lat: -20.4610,
    lng: -54.6152,
    endereco: "Av. Calógeras, 2050 — Centro",
    horario: "Mo-Fr 07:30-17:30; Sa 07:30-13:30",
    telefone: "(67) 3321-3521",
  },
  {
    id: "cgr-f3",
    nome: "Feira do Horto Florestal",
    categoria: "feiras",
    categoriaLabel: "Feira",
    emoji: "🛍️",
    cor: "from-pink-400 to-rose-500",
    lat: -20.4422,
    lng: -54.5927,
    endereco: "Parque Horto Florestal — Bairro Novos Estados",
    horario: "Sa 07:00-13:00",
  },

  // ──────────── SHOWS ────────────
  {
    id: "cgr-s1",
    nome: "Arena CG — Shows & Eventos",
    categoria: "shows",
    categoriaLabel: "Arena",
    emoji: "🎵",
    cor: "from-violet-600 to-purple-800",
    lat: -20.4930,
    lng: -54.6150,
    endereco: "Av. Gury Marques, 5000 — Pioneiros",
  },
  {
    id: "cgr-s2",
    nome: "Clube de Campo de Campo Grande",
    categoria: "shows",
    categoriaLabel: "Show",
    emoji: "🎵",
    cor: "from-violet-600 to-purple-800",
    lat: -20.5100,
    lng: -54.6450,
    endereco: "Av. Duque de Caxias — Carandá Bosque",
    horario: "Fr-Sa 20:00-02:00",
  },

  // ──────────── ESPORTES ────────────
  {
    id: "cgr-e1",
    nome: "Estádio Universitário Morenão",
    categoria: "esportes",
    categoriaLabel: "Estádio",
    emoji: "⚽",
    cor: "from-emerald-500 to-teal-600",
    lat: -20.4544,
    lng: -54.5981,
    endereco: "Av. Universitária s/n — UFMS",
    website: "https://www.operario.com.br",
  },
  {
    id: "cgr-e2",
    nome: "Centro Olímpico de Campo Grande",
    categoria: "esportes",
    categoriaLabel: "Poliesportivo",
    emoji: "⚽",
    cor: "from-emerald-500 to-teal-600",
    lat: -20.4570,
    lng: -54.6010,
    endereco: "Av. Afonso Pena, 7350 — Centro-Oeste",
    horario: "Mo-Fr 07:00-21:00; Sa 07:00-17:00",
  },
  {
    id: "cgr-e3",
    nome: "Club Náutico Campo Grande",
    categoria: "esportes",
    categoriaLabel: "Clube",
    emoji: "⚽",
    cor: "from-emerald-500 to-teal-600",
    lat: -20.5200,
    lng: -54.6700,
    endereco: "Rodovia BR-163, km 2 — Saída para Sidrolândia",
    horario: "Sa-Su 08:00-18:00",
  },
];

export function getCGPlacesByCategoria(cats: string[]): Place[] {
  if (!cats.length || cats.includes("todos")) return CAMPO_GRANDE;
  return CAMPO_GRANDE.filter((p) => cats.includes(p.categoria));
}
