export type Category =
  | "todos"
  | "shows"
  | "bares"
  | "restaurantes"
  | "parques"
  | "feiras"
  | "cultura"
  | "museus"
  | "esportes";

export interface Evento {
  id: string;
  titulo: string;
  categoria: Category;
  categoriaLabel: string;
  data: string;
  hora: string;
  local: string;
  endereco: string;
  cidade: string;
  descricao: string;
  preco: string;
  emoji: string;
  cor: string;
  destaque?: boolean;
  tags: string[];
}

export const categorias: { id: Category; label: string; emoji: string }[] = [
  { id: "todos", label: "Todos", emoji: "✨" },
  { id: "shows", label: "Shows", emoji: "🎵" },
  { id: "bares", label: "Bares", emoji: "🍺" },
  { id: "restaurantes", label: "Restaurantes", emoji: "🍽️" },
  { id: "parques", label: "Parques", emoji: "🌿" },
  { id: "feiras", label: "Feiras", emoji: "🛍️" },
  { id: "cultura", label: "Cultura", emoji: "🎭" },
  { id: "museus", label: "Museus", emoji: "🏛️" },
  { id: "esportes", label: "Esportes", emoji: "⚽" },
];

export const eventos: Evento[] = [
  {
    id: "1",
    titulo: "Festival de Jazz & Blues",
    categoria: "shows",
    categoriaLabel: "Show",
    data: "Hoje",
    hora: "20:00",
    local: "Anfiteatro da Concha Acústica",
    endereco: "Av. das Nações, s/n",
    cidade: "Brasília, DF",
    descricao: "Uma noite inesquecível com os melhores músicos de jazz e blues do Brasil. Traz aquela pessoa especial e aproveita o fim de semana com muita música boa ao ar livre.",
    preco: "R$ 40",
    emoji: "🎷",
    cor: "from-violet-600 to-purple-800",
    destaque: true,
    tags: ["Jazz", "Blues", "Ao vivo", "Ao ar livre"],
  },
  {
    id: "2",
    titulo: "Feirão Hippie de Arte e Artesanato",
    categoria: "feiras",
    categoriaLabel: "Feira",
    data: "Hoje",
    hora: "08:00 – 18:00",
    local: "Feira dos Importados",
    endereco: "SBS Qd. 02, Bloco M",
    cidade: "Brasília, DF",
    descricao: "A maior feira de artesanato da cidade! Artesanatos, roupas, bijuterias, comida típica e muita cultura. Entrada gratuita, venha com a família!",
    preco: "Gratuito",
    emoji: "🧶",
    cor: "from-amber-400 to-orange-500",
    destaque: true,
    tags: ["Artesanato", "Familia", "Gratuito"],
  },
  {
    id: "3",
    titulo: "Noite de Samba no Botequim",
    categoria: "bares",
    categoriaLabel: "Bar",
    data: "Hoje",
    hora: "21:00",
    local: "Bar do Beto",
    endereco: "CLS 204 Bloco B, Loja 10",
    cidade: "Brasília, DF",
    descricao: "Toda segunda-feira tem samba no boteco mais tradicional de Brasília. Petiscos deliciosos, cerveja gelada e samba de raiz até meia-noite.",
    preco: "Consumação mín. R$ 30",
    emoji: "🥁",
    cor: "from-green-500 to-emerald-700",
    destaque: false,
    tags: ["Samba", "Boteco", "Petiscos"],
  },
  {
    id: "4",
    titulo: "Corrida & Caminhada no Parque",
    categoria: "parques",
    categoriaLabel: "Parque",
    data: "Hoje",
    hora: "06:30",
    local: "Parque da Cidade Sarah Kubitschek",
    endereco: "Eixo Monumental",
    cidade: "Brasília, DF",
    descricao: "Grupo de corrida e caminhada aberto a todos. Percurso de 5km pelo parque com monitores. Ideal para quem quer começar a se exercitar ao ar livre.",
    preco: "Gratuito",
    emoji: "🏃",
    cor: "from-teal-400 to-cyan-600",
    destaque: false,
    tags: ["Esporte", "Saúde", "Gratuito", "Família"],
  },
  {
    id: "5",
    titulo: "Exposição: Cores do Cerrado",
    categoria: "museus",
    categoriaLabel: "Museu",
    data: "Hoje",
    hora: "10:00 – 18:00",
    local: "Museu Nacional de Brasília",
    endereco: "Esplanada dos Ministérios",
    cidade: "Brasília, DF",
    descricao: "Exposição fotográfica que celebra a biodiversidade do Cerrado brasileiro. Mais de 200 fotografias de artistas locais retratando paisagens, animais e flora.",
    preco: "R$ 10 (meia R$ 5)",
    emoji: "🌵",
    cor: "from-yellow-500 to-amber-600",
    destaque: true,
    tags: ["Arte", "Fotografia", "Cerrado", "Cultura"],
  },
  {
    id: "6",
    titulo: "Rodada de Stand-up Comedy",
    categoria: "cultura",
    categoriaLabel: "Cultura",
    data: "Hoje",
    hora: "20:30",
    local: "Teatro do SESC",
    endereco: "CLN 506, Bloco A",
    cidade: "Brasília, DF",
    descricao: "4 comediantes em cena por 2 horas de gargalhadas garantidas. Espetáculo adulto, proibido para menores de 18 anos.",
    preco: "R$ 35",
    emoji: "😂",
    cor: "from-pink-500 to-rose-600",
    destaque: false,
    tags: ["Comédia", "Teatro", "Adulto"],
  },
  {
    id: "7",
    titulo: "Flamengo vs Brasiliense",
    categoria: "esportes",
    categoriaLabel: "Esporte",
    data: "Hoje",
    hora: "19:00",
    local: "Estádio Bezerrão",
    endereco: "Setor Central, Gama",
    cidade: "Gama, DF",
    descricao: "Jogo amistoso entre Flamengo e Brasiliense. Arquibancada lotada, muita emoção e futebol de alto nível na capital federal.",
    preco: "R$ 20",
    emoji: "⚽",
    cor: "from-red-500 to-red-700",
    destaque: true,
    tags: ["Futebol", "Amistoso", "Família"],
  },
  {
    id: "8",
    titulo: "Almoço Especial de Segunda",
    categoria: "restaurantes",
    categoriaLabel: "Restaurante",
    data: "Hoje",
    hora: "11:30 – 15:00",
    local: "Restaurante Sabor do Brasil",
    endereco: "SCN Qd. 04, Bloco A",
    cidade: "Brasília, DF",
    descricao: "Buffet livre com mais de 30 pratos da culinária brasileira, incluindo opções vegetarianas e veganas. Sobremesa inclusa.",
    preco: "R$ 55/pessoa",
    emoji: "🍲",
    cor: "from-orange-400 to-red-500",
    destaque: false,
    tags: ["Buffet", "Culinária Brasileira", "Vegetariano"],
  },
  {
    id: "9",
    titulo: "Show de Funk e Pagode",
    categoria: "shows",
    categoriaLabel: "Show",
    data: "Amanhã",
    hora: "22:00",
    local: "Arena BSB",
    endereco: "SGCV Lote 16",
    cidade: "Brasília, DF",
    descricao: "A festa que todo mundo esperava! DJs convidados, open bar por 3 horas e muito pagode e funk para animar a madrugada.",
    preco: "R$ 60",
    emoji: "🎤",
    cor: "from-violet-500 to-indigo-700",
    destaque: false,
    tags: ["Funk", "Pagode", "Open Bar", "Balada"],
  },
  {
    id: "10",
    titulo: "Feira Orgânica do Produtor",
    categoria: "feiras",
    categoriaLabel: "Feira",
    data: "Amanhã",
    hora: "07:00 – 12:00",
    local: "Superquadra Norte 204",
    endereco: "SQN 204",
    cidade: "Brasília, DF",
    descricao: "Feira com produtores locais trazendo frutas, legumes, ovos e mel orgânicos. Valorize o produtor local e leve saúde para casa.",
    preco: "Gratuito",
    emoji: "🥦",
    cor: "from-green-400 to-lime-600",
    destaque: false,
    tags: ["Orgânico", "Feira", "Saúde", "Gratuito"],
  },
  {
    id: "11",
    titulo: "Yoga ao Amanhecer",
    categoria: "parques",
    categoriaLabel: "Parque",
    data: "Amanhã",
    hora: "06:00",
    local: "Jardim Botânico de Brasília",
    endereco: "SMPW Quadra 04",
    cidade: "Brasília, DF",
    descricao: "Aula gratuita de yoga ao ar livre no jardim botânico. Todos os níveis bem-vindos. Leve seu tapete e água.",
    preco: "Gratuito",
    emoji: "🧘",
    cor: "from-blue-400 to-cyan-500",
    destaque: false,
    tags: ["Yoga", "Bem-estar", "Gratuito", "Natureza"],
  },
  {
    id: "12",
    titulo: "Happy Hour com DJ",
    categoria: "bares",
    categoriaLabel: "Bar",
    data: "Amanhã",
    hora: "18:00",
    local: "Terraço Bar Rooftop",
    endereco: "SCLN 405, Bloco A",
    cidade: "Brasília, DF",
    descricao: "Happy hour no rooftop mais cool de Brasília com vista para a cidade. Drinks especiais com 30% de desconto até as 20h e DJ a partir das 19h.",
    preco: "Consumação mín. R$ 50",
    emoji: "🍹",
    cor: "from-pink-400 to-fuchsia-600",
    destaque: true,
    tags: ["Happy Hour", "DJ", "Rooftop", "Drinks"],
  },
  {
    id: "13",
    titulo: "Peça: O Auto da Compadecida",
    categoria: "cultura",
    categoriaLabel: "Cultura",
    data: "Amanhã",
    hora: "19:30",
    local: "Teatro Nacional Claudio Santoro",
    endereco: "Setor Cultural Norte",
    cidade: "Brasília, DF",
    descricao: "A clássica obra de Ariano Suassuna ganha nova montagem com elenco premiado. Espetáculo de 2h30 com intervalo.",
    preco: "R$ 50 (meia R$ 25)",
    emoji: "🎭",
    cor: "from-purple-500 to-violet-700",
    destaque: true,
    tags: ["Teatro", "Clássico", "Literatura"],
  },
  {
    id: "14",
    titulo: "Tour Guiado: Arquitetura de Niemeyer",
    categoria: "museus",
    categoriaLabel: "Museu",
    data: "Amanhã",
    hora: "09:00",
    local: "Ponto de encontro: Memorial JK",
    endereco: "Eixo Monumental Oeste",
    cidade: "Brasília, DF",
    descricao: "Tour a pé pelos principais monumentos projetados por Oscar Niemeyer. Guia especializado, duração de 3 horas, máximo 20 pessoas.",
    preco: "R$ 25",
    emoji: "🏛️",
    cor: "from-slate-500 to-zinc-700",
    destaque: false,
    tags: ["Arquitetura", "Tour", "Niemeyer", "Cultura"],
  },
  {
    id: "15",
    titulo: "Semifinal de Basquete 3×3",
    categoria: "esportes",
    categoriaLabel: "Esporte",
    data: "Amanhã",
    hora: "14:00",
    local: "Poliesportivo Nilson Nelson",
    endereco: "Eixo Monumental",
    cidade: "Brasília, DF",
    descricao: "Semifinal do campeonato distrital de basquete 3×3. Entrada gratuita para a torcida. Venha apoiar as equipes locais!",
    preco: "Gratuito",
    emoji: "🏀",
    cor: "from-orange-500 to-amber-600",
    destaque: false,
    tags: ["Basquete", "Campeonato", "Gratuito"],
  },
  {
    id: "16",
    titulo: "Jantar Romântico com Vista",
    categoria: "restaurantes",
    categoriaLabel: "Restaurante",
    data: "Amanhã",
    hora: "19:00",
    local: "Restaurante Torre de TV",
    endereco: "Eixo Monumental, Torre de TV",
    cidade: "Brasília, DF",
    descricao: "Jantar especial no restaurante giratório no alto da Torre de TV. Menu degustação com 5 pratos, harmonização com vinhos incluída.",
    preco: "R$ 180/casal",
    emoji: "🕯️",
    cor: "from-rose-400 to-pink-600",
    destaque: false,
    tags: ["Romântico", "Jantar", "Vista"],
  },
  {
    id: "17",
    titulo: "Rock Garage com Bandas Locais",
    categoria: "shows",
    categoriaLabel: "Show",
    data: "Esta semana",
    hora: "21:00",
    local: "Porão do Rock",
    endereco: "CLN 206, Bloco B",
    cidade: "Brasília, DF",
    descricao: "3 bandas de rock independente em uma noite só. Entrada com 1kg de alimento não perecível. Apoie a música local e a solidariedade.",
    preco: "1kg de alimento",
    emoji: "🎸",
    cor: "from-gray-700 to-zinc-900",
    destaque: false,
    tags: ["Rock", "Local", "Solidário"],
  },
  {
    id: "18",
    titulo: "Picnic no Parque com Food Trucks",
    categoria: "parques",
    categoriaLabel: "Parque",
    data: "Esta semana",
    hora: "10:00 – 20:00",
    local: "Parque Ecológico Ezio Lombardi",
    endereco: "SMPW Quadra 26",
    cidade: "Brasília, DF",
    descricao: "Evento de picnic com food trucks, música ao vivo, atividades para crianças e muito espaço verde para relaxar. Leve sua cadeira ou manta!",
    preco: "Gratuito (consumação à parte)",
    emoji: "🧺",
    cor: "from-lime-400 to-green-600",
    destaque: true,
    tags: ["Picnic", "Família", "Food Trucks", "Crianças"],
  },
  {
    id: "19",
    titulo: "Forró Universitário",
    categoria: "shows",
    categoriaLabel: "Show",
    data: "Esta semana",
    hora: "22:00",
    local: "Clube do Choro",
    endereco: "SDS Bloco K, Entrada 27",
    cidade: "Brasília, DF",
    descricao: "A melhor noite de forró universitário da cidade. DJ Forró e banda ao vivo. Aula de forró gratuita a partir das 21h para iniciantes.",
    preco: "R$ 20",
    emoji: "💃",
    cor: "from-yellow-400 to-orange-500",
    destaque: false,
    tags: ["Forró", "Dança", "Música ao Vivo"],
  },
  {
    id: "20",
    titulo: "Museu da República",
    categoria: "museus",
    categoriaLabel: "Museu",
    data: "Hoje",
    hora: "10:00 – 17:30",
    local: "Museu da República",
    endereco: "Esplanada dos Ministérios",
    cidade: "Brasília, DF",
    descricao: "O museu apresenta a história política do Brasil com acervo único de documentos, objetos e obras de arte do período republicano.",
    preco: "R$ 5 (gratuito às terças)",
    emoji: "📜",
    cor: "from-amber-600 to-yellow-700",
    destaque: false,
    tags: ["História", "Política", "Museu"],
  },
  {
    id: "21",
    titulo: "Feira de Antiguidades",
    categoria: "feiras",
    categoriaLabel: "Feira",
    data: "Esta semana",
    hora: "09:00 – 17:00",
    local: "Calçadão da Asa Norte",
    endereco: "SBN Qd. 01",
    cidade: "Brasília, DF",
    descricao: "Centenas de expositores com antiguidades, colecionáveis, vinil, móveis vintage e muito mais. Um tesouro escondido no coração de Brasília.",
    preco: "Gratuito",
    emoji: "🪆",
    cor: "from-stone-500 to-amber-700",
    destaque: false,
    tags: ["Antiguidades", "Vinil", "Vintage", "Gratuito"],
  },
  {
    id: "22",
    titulo: "Maratona de Cinema Indie",
    categoria: "cultura",
    categoriaLabel: "Cultura",
    data: "Esta semana",
    hora: "14:00",
    local: "Cine Cultura de Brasília",
    endereco: "SCN Qd. 04, Bloco A",
    cidade: "Brasília, DF",
    descricao: "3 filmes independentes brasileiros em sequência. Debate com diretores após cada exibição. Pipoca e refrigerante inclusos.",
    preco: "R$ 30 (pacote 3 filmes)",
    emoji: "🎬",
    cor: "from-indigo-500 to-blue-700",
    destaque: false,
    tags: ["Cinema", "Independente", "Debate"],
  },
  {
    id: "23",
    titulo: "Treino Funcional ao Ar Livre",
    categoria: "esportes",
    categoriaLabel: "Esporte",
    data: "Hoje",
    hora: "07:00",
    local: "Pontão do Lago Sul",
    endereco: "Lago Sul",
    cidade: "Brasília, DF",
    descricao: "Treino funcional gratuito orgnizado por personal trainers voluntários. Leve água, tênis e roupa confortável. Todos os níveis são bem-vindos.",
    preco: "Gratuito",
    emoji: "💪",
    cor: "from-cyan-500 to-blue-600",
    destaque: false,
    tags: ["Funcional", "Treino", "Gratuito", "Saúde"],
  },
  {
    id: "24",
    titulo: "Boteco da Esquina — Clássico",
    categoria: "bares",
    categoriaLabel: "Bar",
    data: "Hoje",
    hora: "17:00",
    local: "Boteco do Zé",
    endereco: "SQS 308, Bloco G",
    cidade: "Brasília, DF",
    descricao: "O boteco mais tradicional da Asa Sul. Bolinho de bacalhau premiado, tiragosto variado e a melhor imperial da cidade. Sempre animado!",
    preco: "Consumação livre",
    emoji: "🍻",
    cor: "from-yellow-500 to-amber-600",
    destaque: false,
    tags: ["Boteco", "Petisco", "Tradicional"],
  },
  {
    id: "25",
    titulo: "Corrida de Rua — 5K e 10K",
    categoria: "esportes",
    categoriaLabel: "Esporte",
    data: "Esta semana",
    hora: "07:00",
    local: "Parque da Cidade",
    endereco: "Eixo Monumental Sul",
    cidade: "Brasília, DF",
    descricao: "Corrida de rua com percursos de 5K e 10K pelo Parque da Cidade. Inscrições abertas, camiseta inclusa. Premiação para os três primeiros.",
    preco: "R$ 35 (inscrição)",
    emoji: "🏅",
    cor: "from-emerald-500 to-teal-600",
    destaque: false,
    tags: ["Corrida", "5K", "10K", "Esporte"],
  },
];

export function getEventoById(id: string): Evento | undefined {
  return eventos.find((e) => e.id === id);
}

export function getEventosByCategoria(categoria: Category): Evento[] {
  if (categoria === "todos") return eventos;
  return eventos.filter((e) => e.categoria === categoria);
}

export function getEventosDestaque(): Evento[] {
  return eventos.filter((e) => e.destaque);
}

export function searchEventos(query: string): Evento[] {
  const q = query.toLowerCase();
  return eventos.filter(
    (e) =>
      e.titulo.toLowerCase().includes(q) ||
      e.local.toLowerCase().includes(q) ||
      e.tags.some((t) => t.toLowerCase().includes(q))
  );
}
